name: Deploy to Koyeb
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: "${{ secrets.KOYEB_TOKEN }}"
      - name: Deploy to Koyeb
        run: |
          koyeb deploy . test/main \
            --instance-type medium \
            --region was \
            --archive-builder docker \
            --archive-docker-dockerfile ./Dockerfile \
            --privileged \
            --type web \
            --port 4444:http \
            --route /:4444
